name: Deploy AELI Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test || echo "No tests specified yet"

  deploy:
    name: 🚀 Deploy to VPS
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 51.79.68.223
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/my-app
            
            # 1. Mise à jour du code
            git pull origin main
            
            # 2. Redémarrage avec la nouvelle syntaxe (SANS le tiret)
            # On utilise -T pour éviter les erreurs de terminal (TTY) dans le CI
            sudo docker compose up -d --build
            
            # 3. Application des migrations Sequelize
            sudo docker compose exec -T api npx sequelize-cli db:migrate
            
            # 4. Nettoyage
            sudo docker image prune -f
            
            # 5. Statut final
            sudo docker ps
